top10_mock_data = [
    {
        "player_name": "alutemu",
        "rating": 16564,
        "rank": 1,
        "region": "AP",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 1,
    },
    {
        "player_name": "seseisei",
        "rating": 16097,
        "rank": 2,
        "region": "AP",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 2,
    },
    {
        "player_name": "matsuri",
        "rating": 16017,
        "rank": 3,
        "region": "AP",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 3,
    },
    {
        "player_name": "梁瀬",
        "rating": 15912,
        "rank": 4,
        "region": "AP",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 4,
    },
    {
        "player_name": "k3rsm",
        "rating": 15784,
        "rank": 5,
        "region": "AP",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 5,
    },
    {
        "player_name": "hsmt",
        "rating": 15745,
        "rank": 6,
        "region": "AP",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 6,
    },
    {
        "player_name": "reangle",
        "rating": 15386,
        "rank": 7,
        "region": "AP",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 7,
    },
    {
        "player_name": "yoshiyuki",
        "rating": 15373,
        "rank": 8,
        "region": "AP",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 8,
    },
    {
        "player_name": "satellite",
        "rating": 15153,
        "rank": 9,
        "region": "AP",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 9,
    },
    {
        "player_name": "gaiabot",
        "rating": 15058,
        "rank": 10,
        "region": "AP",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 10,
    },
    {
        "player_name": "ranpuz",
        "rating": 17477,
        "rank": 1,
        "region": "AP",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 1,
    },
    {
        "player_name": "ちぇいん",
        "rating": 17238,
        "rank": 2,
        "region": "AP",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 2,
    },
    {
        "player_name": "limedrake",
        "rating": 15526,
        "rank": 3,
        "region": "AP",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 3,
    },
    {
        "player_name": "飛馬",
        "rating": 14074,
        "rank": 4,
        "region": "AP",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 4,
    },
    {
        "player_name": "saninobe",
        "rating": 13778,
        "rank": 5,
        "region": "AP",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 5,
    },
    {
        "player_name": "moku",
        "rating": 13547,
        "rank": 6,
        "region": "AP",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 6,
    },
    {
        "player_name": "bwb",
        "rating": 13298,
        "rank": 7,
        "region": "AP",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 7,
    },
    {
        "player_name": "jyun19",
        "rating": 13185,
        "rank": 8,
        "region": "AP",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 8,
    },
    {
        "player_name": "syogo",
        "rating": 13095,
        "rank": 9,
        "region": "AP",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 9,
    },
    {
        "player_name": "citruslimon",
        "rating": 13057,
        "rank": 10,
        "region": "AP",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 10,
    },
    {
        "player_name": "最长的河",
        "rating": 20275,
        "rank": 1,
        "region": "CN",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 1,
    },
    {
        "player_name": "虎牙丨郭枫荷",
        "rating": 20271,
        "rank": 2,
        "region": "CN",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 2,
    },
    {
        "player_name": "zorgo",
        "rating": 20068,
        "rank": 3,
        "region": "CN",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 3,
    },
    {
        "player_name": "大安庄园欢迎你",
        "rating": 19778,
        "rank": 4,
        "region": "CN",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 4,
    },
    {
        "player_name": "抖音丨有局丨小狼",
        "rating": 19579,
        "rank": 5,
        "region": "CN",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 5,
    },
    {
        "player_name": "虎牙丨尖尖箭",
        "rating": 19568,
        "rank": 6,
        "region": "CN",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 6,
    },
    {
        "player_name": "jeef",
        "rating": 19466,
        "rank": 7,
        "region": "CN",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 7,
    },
    {
        "player_name": "lighting",
        "rating": 19457,
        "rank": 8,
        "region": "CN",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 8,
    },
    {
        "player_name": "一只逗逼",
        "rating": 19270,
        "rank": 9,
        "region": "CN",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 9,
    },
    {
        "player_name": "至魔太一剑穹狂帝",
        "rating": 19269,
        "rank": 10,
        "region": "CN",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 10,
    },
    {
        "player_name": "抖音华星望月",
        "rating": 27131,
        "rank": 1,
        "region": "CN",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 1,
    },
    {
        "player_name": "夏卿卿卿卿",
        "rating": 25483,
        "rank": 2,
        "region": "CN",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 2,
    },
    {
        "player_name": "空心人不是空心菜",
        "rating": 24068,
        "rank": 3,
        "region": "CN",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 3,
    },
    {
        "player_name": "炉石风暴",
        "rating": 24027,
        "rank": 4,
        "region": "CN",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 4,
    },
    {
        "player_name": "樱和抱月永远一起",
        "rating": 23358,
        "rank": 5,
        "region": "CN",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 5,
    },
    {
        "player_name": "无奈输的好奇葩",
        "rating": 22635,
        "rank": 6,
        "region": "CN",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 6,
    },
    {
        "player_name": "为所欲为丶冒泡",
        "rating": 21988,
        "rank": 7,
        "region": "CN",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 7,
    },
    {
        "player_name": "夏天",
        "rating": 21550,
        "rank": 8,
        "region": "CN",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 8,
    },
    {
        "player_name": "huyahxry",
        "rating": 21200,
        "rank": 9,
        "region": "CN",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 9,
    },
    {
        "player_name": "萌萌哒条码",
        "rating": 20757,
        "rank": 10,
        "region": "CN",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 10,
    },
    {
        "player_name": "леший",
        "rating": 17511,
        "rank": 1,
        "region": "EU",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 1,
    },
    {
        "player_name": "стоякбездела",
        "rating": 17278,
        "rank": 2,
        "region": "EU",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 2,
    },
    {
        "player_name": "mativ",
        "rating": 16429,
        "rank": 3,
        "region": "EU",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 3,
    },
    {
        "player_name": "slyders",
        "rating": 16256,
        "rank": 4,
        "region": "EU",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 4,
    },
    {
        "player_name": "hsmt",
        "rating": 16198,
        "rank": 5,
        "region": "EU",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 5,
    },
    {
        "player_name": "bendrikus",
        "rating": 15804,
        "rank": 6,
        "region": "EU",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 6,
    },
    {
        "player_name": "huyaguo",
        "rating": 15596,
        "rank": 7,
        "region": "EU",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 7,
    },
    {
        "player_name": "guddummit",
        "rating": 15544,
        "rank": 8,
        "region": "EU",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 8,
    },
    {
        "player_name": "benice",
        "rating": 15497,
        "rank": 9,
        "region": "EU",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 9,
    },
    {
        "player_name": "xqn",
        "rating": 15476,
        "rank": 10,
        "region": "EU",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 10,
    },
    {
        "player_name": "смелыйвомбат",
        "rating": 17603,
        "rank": 1,
        "region": "EU",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 1,
    },
    {
        "player_name": "gusyra",
        "rating": 17319,
        "rank": 2,
        "region": "EU",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 2,
    },
    {
        "player_name": "tedjefferson",
        "rating": 17302,
        "rank": 3,
        "region": "EU",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 3,
    },
    {
        "player_name": "flameloa",
        "rating": 16619,
        "rank": 4,
        "region": "EU",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 4,
    },
    {
        "player_name": "yorickjoo",
        "rating": 15631,
        "rank": 5,
        "region": "EU",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 5,
    },
    {
        "player_name": "igeenger",
        "rating": 15521,
        "rank": 6,
        "region": "EU",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 6,
    },
    {
        "player_name": "moonlight",
        "rating": 15519,
        "rank": 7,
        "region": "EU",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 7,
    },
    {
        "player_name": "hugebang",
        "rating": 15470,
        "rank": 8,
        "region": "EU",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 8,
    },
    {
        "player_name": "мэйбл",
        "rating": 15430,
        "rank": 9,
        "region": "EU",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 9,
    },
    {
        "player_name": "seynar",
        "rating": 15409,
        "rank": 10,
        "region": "EU",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 10,
    },
    {
        "player_name": "jeef",
        "rating": 18697,
        "rank": 1,
        "region": "NA",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 1,
    },
    {
        "player_name": "beterbabbit",
        "rating": 17306,
        "rank": 2,
        "region": "NA",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 2,
    },
    {
        "player_name": "lyme",
        "rating": 16512,
        "rank": 3,
        "region": "NA",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 3,
    },
    {
        "player_name": "matthew",
        "rating": 16184,
        "rank": 4,
        "region": "NA",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 4,
    },
    {
        "player_name": "hsmt",
        "rating": 16077,
        "rank": 5,
        "region": "NA",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 5,
    },
    {
        "player_name": "吴伟杰",
        "rating": 15017,
        "rank": 6,
        "region": "NA",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 6,
    },
    {
        "player_name": "dog",
        "rating": 14777,
        "rank": 7,
        "region": "NA",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 7,
    },
    {
        "player_name": "an1honysch2",
        "rating": 14704,
        "rank": 8,
        "region": "NA",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 8,
    },
    {
        "player_name": "herusia",
        "rating": 14610,
        "rank": 9,
        "region": "NA",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 9,
    },
    {
        "player_name": "dreamcreek",
        "rating": 14299,
        "rank": 10,
        "region": "NA",
        "game_mode": "0",
        "day_start": "2025-07-09",
        "row_num": 10,
    },
    {
        "player_name": "upsetking",
        "rating": 20525,
        "rank": 1,
        "region": "NA",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 1,
    },
    {
        "player_name": "ayy",
        "rating": 20366,
        "rank": 2,
        "region": "NA",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 2,
    },
    {
        "player_name": "fuglackh",
        "rating": 19512,
        "rank": 3,
        "region": "NA",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 3,
    },
    {
        "player_name": "willxking",
        "rating": 19005,
        "rank": 4,
        "region": "NA",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 4,
    },
    {
        "player_name": "zachiswack",
        "rating": 18641,
        "rank": 5,
        "region": "NA",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 5,
    },
    {
        "player_name": "paleguyhi",
        "rating": 18641,
        "rank": 6,
        "region": "NA",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 6,
    },
    {
        "player_name": "saphirexx",
        "rating": 16758,
        "rank": 7,
        "region": "NA",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 7,
    },
    {
        "player_name": "educatedc",
        "rating": 16754,
        "rank": 8,
        "region": "NA",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 8,
    },
    {
        "player_name": "exodius003",
        "rating": 16509,
        "rank": 9,
        "region": "NA",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 9,
    },
    {
        "player_name": "jared095",
        "rating": 16438,
        "rank": 10,
        "region": "NA",
        "game_mode": "1",
        "day_start": "2025-07-09",
        "row_num": 10,
    },
]
