AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Supabase-only Lambda stack for HSBG automation

Parameters:
  DBHost:
    Type: String
    Description: Database host
  DBName:
    Type: String
    Description: Database name
  DBUser:
    Type: String
    Description: Database user
  DBPassword:
    Type: String
    Description: Database password
    NoEcho: true
  DBPort:
    Type: String
    Description: Database port
    Default: "5432"
  TwitchLiveCheckClientId:
    Type: String
    Description: Twitch client ID
  TwitchLiveCheckSecret:
    Type: String
    Description: Twitch client secret
    NoEcho: true
  AlertEmail:
    Type: String
    Description: Email address for Lambda error alerts
    Default: ""

Resources:

  CurrentLeaderboardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: current_leaderboard/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 900
      MemorySize: 256
      Environment:
        Variables:
          DB_HOST: !Ref DBHost
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          DB_PORT: !Ref DBPort
          TWITCH_LIVE_CHECK_CLIENT_ID: !Ref TwitchLiveCheckClientId
          TWITCH_LIVE_CHECK_SECRET: !Ref TwitchLiveCheckSecret
      Events:
        ScheduledUpdate:
          Type: Schedule
          Properties:
            Schedule: rate(12 hours)

  LeaderboardSnapshotsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: leaderboard_snapshots/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 300
      MemorySize: 256
      Environment:
        Variables:
          DB_HOST: !Ref DBHost
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          DB_PORT: !Ref DBPort
          TWITCH_LIVE_CHECK_CLIENT_ID: !Ref TwitchLiveCheckClientId
          TWITCH_LIVE_CHECK_SECRET: !Ref TwitchLiveCheckSecret
      Events:
        ScheduledUpdate:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)

  FetchNewsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: fetch_news/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 300
      MemorySize: 256
      Environment:
        Variables:
          DB_HOST: !Ref DBHost
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          DB_PORT: !Ref DBPort
          TWITCH_LIVE_CHECK_CLIENT_ID: !Ref TwitchLiveCheckClientId
          TWITCH_LIVE_CHECK_SECRET: !Ref TwitchLiveCheckSecret
      Events:
        ScheduledUpdate:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)

  TwitchLiveCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: twitch_live_check/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 300
      MemorySize: 128
      Environment:
        Variables:
          DB_HOST: !Ref DBHost
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          DB_PORT: !Ref DBPort
          TWITCH_LIVE_CHECK_CLIENT_ID: !Ref TwitchLiveCheckClientId
          TWITCH_LIVE_CHECK_SECRET: !Ref TwitchLiveCheckSecret
      Events:
        ScheduledUpdate:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)

  UpdateEntitiesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update_entities/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 900
      MemorySize: 512
      Environment:
        Variables:
          DB_HOST: !Ref DBHost
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          DB_PORT: !Ref DBPort
          TWITCH_LIVE_CHECK_CLIENT_ID: !Ref TwitchLiveCheckClientId
          TWITCH_LIVE_CHECK_SECRET: !Ref TwitchLiveCheckSecret
      Events:
        ScheduledUpdate:
          Type: Schedule
          Properties:
            Schedule: rate(4 hours)

  # SNS Topic for Lambda Error Alerts
  LambdaErrorTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Lambda Error Alerts
      TopicName: hsbg-lambda-error-alerts

  # SNS Subscription (only created if AlertEmail is provided)
  LambdaErrorSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasAlertEmail
    Properties:
      Protocol: email
      TopicArn: !Ref LambdaErrorTopic
      Endpoint: !Ref AlertEmail

  # CloudWatch Alarm for CurrentLeaderboardFunction
  CurrentLeaderboardErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: CurrentLeaderboardFunction-Errors
      AlarmDescription: Alert when CurrentLeaderboardFunction has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref CurrentLeaderboardFunction
      AlarmActions:
        - !Ref LambdaErrorTopic

  # CloudWatch Alarm for LeaderboardSnapshotsFunction
  LeaderboardSnapshotsErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: LeaderboardSnapshotsFunction-Errors
      AlarmDescription: Alert when LeaderboardSnapshotsFunction has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref LeaderboardSnapshotsFunction
      AlarmActions:
        - !Ref LambdaErrorTopic

  # CloudWatch Alarm for FetchNewsFunction
  FetchNewsErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: FetchNewsFunction-Errors
      AlarmDescription: Alert when FetchNewsFunction has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref FetchNewsFunction
      AlarmActions:
        - !Ref LambdaErrorTopic

  # CloudWatch Alarm for TwitchLiveCheckFunction
  TwitchLiveCheckErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: TwitchLiveCheckFunction-Errors
      AlarmDescription: Alert when TwitchLiveCheckFunction has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref TwitchLiveCheckFunction
      AlarmActions:
        - !Ref LambdaErrorTopic

  # CloudWatch Alarm for UpdateEntitiesFunction
  UpdateEntitiesErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: UpdateEntitiesFunction-Errors
      AlarmDescription: Alert when UpdateEntitiesFunction has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref UpdateEntitiesFunction
      AlarmActions:
        - !Ref LambdaErrorTopic

Conditions:
  HasAlertEmail: !Not [!Equals [!Ref AlertEmail, ""]]