AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Supabase-only Lambda stack for HSBG automation

Parameters:
  DB_HOST:
    Type: String
    Description: Database host
  DB_NAME:
    Type: String
    Description: Database name
  DB_USER:
    Type: String
    Description: Database user
  DB_PASSWORD:
    Type: String
    Description: Database password
    NoEcho: true
  DB_PORT:
    Type: String
    Description: Database port
    Default: "5432"
  TWITCH_LIVE_CHECK_CLIENT_ID:
    Type: String
    Description: Twitch client ID
  TWITCH_LIVE_CHECK_SECRET:
    Type: String
    Description: Twitch client secret
    NoEcho: true

Resources:

  CurrentLeaderboardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: current_leaderboard/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 900
      MemorySize: 256
      Environment:
        Variables:
          DB_HOST: !Ref DB_HOST
          DB_NAME: !Ref DB_NAME
          DB_USER: !Ref DB_USER
          DB_PASSWORD: !Ref DB_PASSWORD
          DB_PORT: !Ref DB_PORT
          TWITCH_LIVE_CHECK_CLIENT_ID: !Ref TWITCH_LIVE_CHECK_CLIENT_ID
          TWITCH_LIVE_CHECK_SECRET: !Ref TWITCH_LIVE_CHECK_SECRET
      Events:
        ScheduledUpdate:
          Type: Schedule
          Properties:
            Schedule: rate(12 hours)

  LeaderboardSnapshotsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: leaderboard_snapshots/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 300
      MemorySize: 256
      Environment:
        Variables:
          DB_HOST: !Ref DB_HOST
          DB_NAME: !Ref DB_NAME
          DB_USER: !Ref DB_USER
          DB_PASSWORD: !Ref DB_PASSWORD
          DB_PORT: !Ref DB_PORT
          TWITCH_LIVE_CHECK_CLIENT_ID: !Ref TWITCH_LIVE_CHECK_CLIENT_ID
          TWITCH_LIVE_CHECK_SECRET: !Ref TWITCH_LIVE_CHECK_SECRET
      Events:
        ScheduledUpdate:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)

  FetchNewsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: fetch_news/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 300
      MemorySize: 256
      Environment:
        Variables:
          DB_HOST: !Ref DB_HOST
          DB_NAME: !Ref DB_NAME
          DB_USER: !Ref DB_USER
          DB_PASSWORD: !Ref DB_PASSWORD
          DB_PORT: !Ref DB_PORT
          TWITCH_LIVE_CHECK_CLIENT_ID: !Ref TWITCH_LIVE_CHECK_CLIENT_ID
          TWITCH_LIVE_CHECK_SECRET: !Ref TWITCH_LIVE_CHECK_SECRET
      Events:
        ScheduledUpdate:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)

  TwitchLiveCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: twitch_live_check/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 300
      MemorySize: 128
      Environment:
        Variables:
          DB_HOST: !Ref DB_HOST
          DB_NAME: !Ref DB_NAME
          DB_USER: !Ref DB_USER
          DB_PASSWORD: !Ref DB_PASSWORD
          DB_PORT: !Ref DB_PORT
          TWITCH_LIVE_CHECK_CLIENT_ID: !Ref TWITCH_LIVE_CHECK_CLIENT_ID
          TWITCH_LIVE_CHECK_SECRET: !Ref TWITCH_LIVE_CHECK_SECRET
      Events:
        ScheduledUpdate:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)

  UpdateEntitiesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update_entities/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 900
      MemorySize: 512
      Environment:
        Variables:
          DB_HOST: !Ref DB_HOST
          DB_NAME: !Ref DB_NAME
          DB_USER: !Ref DB_USER
          DB_PASSWORD: !Ref DB_PASSWORD
          DB_PORT: !Ref DB_PORT
          TWITCH_LIVE_CHECK_CLIENT_ID: !Ref TWITCH_LIVE_CHECK_CLIENT_ID
          TWITCH_LIVE_CHECK_SECRET: !Ref TWITCH_LIVE_CHECK_SECRET
      Events:
        ScheduledUpdate:
          Type: Schedule
          Properties:
            Schedule: rate(4 hours)