AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Supabase-only Lambda stack for HSBG automation

Parameters:
  DBHost:
    Type: String
    Description: Database host
  DBName:
    Type: String
    Description: Database name
  DBUser:
    Type: String
    Description: Database user
  DBPassword:
    Type: String
    Description: Database password
    NoEcho: true
  DBPort:
    Type: String
    Description: Database port
    Default: "5432"
  TwitchLiveCheckClientId:
    Type: String
    Description: Twitch client ID
  TwitchLiveCheckSecret:
    Type: String
    Description: Twitch client secret
    NoEcho: true

Resources:

  CurrentLeaderboardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: current_leaderboard/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 900
      MemorySize: 256
      Environment:
        Variables:
          DB_HOST: !Ref DBHost
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          DB_PORT: !Ref DBPort
          TWITCH_LIVE_CHECK_CLIENT_ID: !Ref TwitchLiveCheckClientId
          TWITCH_LIVE_CHECK_SECRET: !Ref TwitchLiveCheckSecret
      Events:
        ScheduledUpdate:
          Type: Schedule
          Properties:
            Schedule: rate(12 hours)

  LeaderboardSnapshotsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: leaderboard_snapshots/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 300
      MemorySize: 256
      Environment:
        Variables:
          DB_HOST: !Ref DBHost
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          DB_PORT: !Ref DBPort
          TWITCH_LIVE_CHECK_CLIENT_ID: !Ref TwitchLiveCheckClientId
          TWITCH_LIVE_CHECK_SECRET: !Ref TwitchLiveCheckSecret
      Events:
        ScheduledUpdate:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)

  FetchNewsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: fetch_news/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 300
      MemorySize: 256
      Environment:
        Variables:
          DB_HOST: !Ref DBHost
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          DB_PORT: !Ref DBPort
          TWITCH_LIVE_CHECK_CLIENT_ID: !Ref TwitchLiveCheckClientId
          TWITCH_LIVE_CHECK_SECRET: !Ref TwitchLiveCheckSecret
      Events:
        ScheduledUpdate:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)

  TwitchLiveCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: twitch_live_check/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 300
      MemorySize: 128
      Environment:
        Variables:
          DB_HOST: !Ref DBHost
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          DB_PORT: !Ref DBPort
          TWITCH_LIVE_CHECK_CLIENT_ID: !Ref TwitchLiveCheckClientId
          TWITCH_LIVE_CHECK_SECRET: !Ref TwitchLiveCheckSecret
      Events:
        ScheduledUpdate:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)

  UpdateEntitiesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update_entities/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 900
      MemorySize: 512
      Environment:
        Variables:
          DB_HOST: !Ref DBHost
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
          DB_PORT: !Ref DBPort
          TWITCH_LIVE_CHECK_CLIENT_ID: !Ref TwitchLiveCheckClientId
          TWITCH_LIVE_CHECK_SECRET: !Ref TwitchLiveCheckSecret
      Events:
        ScheduledUpdate:
          Type: Schedule
          Properties:
            Schedule: rate(4 hours)