AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploys a cron service to fetch Hearthstone leaderboard data every 3 minutes.
Resources:
  LeaderboardFetchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LeaderboardFetchFunction
      CodeUri: dist/
      Handler: handler.handler
      Timeout: 180 #Three minutes. This seems like overkill,.
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Runtime: python3.8 #Latest. 3.9 is live but not on Lambda.
      Events:
        ThreeMinuteInvoke:
          Type: Schedule
          Properties:
            Schedule: rate(3 minutes) #DELETEME This should work.
      
      
      
    
