AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Hearthstone Battlegrounds Leaderboard Lambda

Resources:
  LeaderboardTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: HearthstoneLeaderboardV2
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 23
        WriteCapacityUnits: 10
      AttributeDefinitions:
        - AttributeName: GameModeServerPlayer
          AttributeType: S
        - AttributeName: GameModeServer
          AttributeType: S
        - AttributeName: CurrentRank
          AttributeType: N
        - AttributeName: PlayerName
          AttributeType: S
        - AttributeName: GameMode
          AttributeType: S
      KeySchema:
        - AttributeName: GameModeServerPlayer
          KeyType: HASH
        - AttributeName: GameModeServer
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: RankLookupIndex
          KeySchema:
            - AttributeName: GameModeServer
              KeyType: HASH
            - AttributeName: CurrentRank
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - PlayerName
              - LatestRating
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 10
        - IndexName: PlayerLookupIndex
          KeySchema:
            - AttributeName: PlayerName
              KeyType: HASH
            - AttributeName: GameMode
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - Server
              - CurrentRank
              - LatestRating
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 5

  MilestoneTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MilestoneTracking
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: SeasonGameModeServer
          AttributeType: S
        - AttributeName: Milestone
          AttributeType: N
      KeySchema:
        - AttributeName: SeasonGameModeServer
          KeyType: HASH
        - AttributeName: Milestone
          KeyType: RANGE

  LeaderboardUpdaterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: dbUpdater.lambda_handler
      Runtime: python3.9
      Timeout: 300
      MemorySize: 256
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LeaderboardTable
        - DynamoDBCrudPolicy:
            TableName: !Ref MilestoneTable
      Environment:
        Variables:
          TABLE_NAME: !Ref LeaderboardTable
          MILESTONE_TABLE_NAME: !Ref MilestoneTable
      Events:
        ScheduledUpdate:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)

  UpdaterErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alert when updater function has errors
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref LeaderboardUpdaterFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref ErrorNotificationTopic

  ErrorNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: LeaderboardUpdaterErrors
