AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploys a cron service to fetch Hearthstone leaderboard data every 3 minutes.
Resources:
  LeaderboardFetchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LeaderboardFetchFunction
      CodeUri: dist/
      Handler: handler.handler
      Timeout: 180 #Three minutes. This seems like overkill,.
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Runtime: python3.8 #Latest. 3.9 is live but not on Lambda.
      Events:
        ThreeMinuteInvoke:
          Type: Schedule
          Properties:
            Schedule: rate(3 minutes) 

  CompositeKeyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "PlayerName"
          AttributeType: "S"
        -
          AttributeName: "Region"
          AttributeType: "S"
      # DynamoDB Free Tier:
      # 25 GB of Storage
      # 25 provisioned Write Capacity Units (WCU)
      # 25 provisioned Read Capacity Units (RCU)
      BillingMode: PROVISIONED 
      ProvisionedThroughput: # We should adjust based on usage.
        ReadCapacityUnits: 10 
        WriteCapacityUnits: 10
      KeySchema: # Composite Key
        -
          AttributeName: "PlayerName"
          KeyType: "HASH" # Partition Key
        -
          AttributeName: "Region"
          KeyType: "RANGE" # Sort Key
      TableName: daily-rating-record-table
      
      
      
    
