alias = {
    'waterloo': 'waterloooooo',
    'jeef': 'jeef',
    'jeff': 'jeef',
    'victor': 'twlevewinshs',
    'sleepy': 'foreversleep',
    'dogdog': 'dog',
    'pockyplays': 'pocky',
    'nina': 'ninaisnoob',
    'liihs': 'lii',
    'purple_hs': 'purple',
    'deathitselfhs': 'deathitself',
    'tylerootd': 'tyler',
    'mrincrediblehs': 'mrincredible',
    'sevel07': 'sevel',
    'jubjoe': 'felix',
    'quinnabr': 'middnie',
}