name: Run tests with docker compose
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker-compose build app-node
        timeout-minutes: 3
      - name: start dynamodb-local
        run: docker-compose up --detach dynamodb-local
        timeout-minutes: 1
      - name: test
        run: docker-compose run app-node
        timeout-minutes: 3