name: Run tests with docker compose
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build pipenv
        run: |
          pip install pipenv
          pipenv install
        timeout-minutes: 3
      - name: start db
        run: docker-compose up -d dynamodb-local
      - name: tests
        run: |
          pipenv run python testApi.py
          pipenv run python testCreateTable.py
          pipenv run python testData.py
          pipenv run python testLeaderboard.py
        timeout-minutes: 7
        working-directory: ./test
      - name: check dynamodb
        run: docker-compose ps
      # - name: test leaderboard table
      #   run: pipenv run python testCreateTable.py
      #   timeout-minutes: 5
      #   working-directory: ./test
      # - name: test leaderboard data
      #   run: pipenv run python testData.py
      #   timeout-minutes: 5
      #   working-directory: ./test
      # - name: test leaderboard bot
      #   run: pipenv run python testLeaderboard.py
      #   timeout-minutes: 5
      #   working-directory: ./test

