name: Run tests with docker compose
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker-compose build app-node
        timeout-minutes: 3
      # - name: test api
      #   run: docker-compose run app-node pipenv run python testApi.py
      #   timeout-minutes: 5
      - name: test leaderboard bot
        run: docker-compose run app-node pipenv run python testLeaderboard.py
        timeout-minutes: 5
